### ISSUE TITLE
XML serialization empty

### ISSUE THREAD

**Issue by StenGruener** [aas-core-works/aas-package3-csharp#32]
Hello,

the example of XML serialization gives an empty string
https://dotnetfiddle.net/VEL2jU

Looks like a bug

BR and thanks for the work
Sten

**Comment by mristin** [comment]
@StenGruener thanks for reporting, I'll have a look at it today!

**Comment by mristin** [comment]
@StenGruener can it be that this issue belongs to https://github.com/aas-core-works/aas-core3.0rc02-csharp?

**Comment by StenGruener** [comment]
@mristin oh sorry, wrong repo, yes!

**Comment by mristin** [comment]
Moved to https://github.com/aas-core-works/aas-core3.0rc02-csharp/issues/66
