### ISSUE TITLE
Submodel Content inside the serialized AssetAdministrationShell JSON

### ISSUE THREAD

**Issue by hmrc87** [aas-core-works/aas-package3-csharp#33]
When I check the examples on https://admin-shell-io.com/5001/ I can see that those have the AAS-Content as well as the Submodel-Content directly inside one .xml file. 

![image](https://github.com/aas-core-works/aas-package3-csharp/assets/1226017/e12c489f-881e-4a56-bbe9-1f35dded12e2)

As far I understand this is not possible with the aas-core-works library since Submodels can only be added to the AssetAdministrationShell Model as IReference.

Therefore the Submodels would be serialized into their own JSON files inside the .aasx-package, correct?

**Comment by mristin** [comment]
Hi @hmrc87 ,

> Therefore the Submodels would be serialized into their own JSON files inside the .aasx-package, correct?

No, the submodels are embedded into Environment class, and referenced from the instances of AssetAdministrationShell.

I suppose the misunderstanding comes from what is the root object: that is the Environment, and not the AssetAdministrationShell.

> As far I understand this is not possible with the aas-core-works library since Submodels can only be added to the AssetAdministrationShell Model as IReference.

You have to deserialize the file as an Environment object.

Important note: I think the example you copy/pasted is AAS V2 which has been obsolete for some time now (2 years?), but I can't tell from the snippet. In V3, the root is explicitly the Environment.

See:
* Formalized meta-model: https://aas-core-works.github.io/aas-core-meta/v3/Environment.html
* AAS XML Schema V3: https://github.com/admin-shell-io/aas-specs/blob/32a2c83bf2f8f991ace47fb6e5ed57e3350314e3/schemas/xml/AAS.xsd#L1342

I'll close the issue, but feel free to re-open if you think there is an error somewhere. Please feel free to ask further questions either way!

**Comment by hmrc87** [comment]
Thanks for clarifying. I am just still confused because of the various different versions out there. AASX Package explorer as it seems doesn't support V3 packages. I thought it would already

**Comment by mristin** [comment]
@hmrc87 you are welcome. Just a small nitpick for other readers: the package format (AASX) did not change between V2 and V3. In contrast, the meta-model did change substantially. The AAS models are hence incompatible, but the packaging format (based on Open Packaging Convention) remained the same.
