### ISSUE TITLE
README referers to .NET 5, not .NET 6

### ISSUE THREAD

**Issue by jh-isw** [aas-core-works/aas-package3-csharp#35]
https://github.com/aas-core-works/aas-package3-csharp/blob/cbb9ad04777e682ac19d7b69267dce58bf15cddc/README.md?plain=1#L20

Since V1.0.0-pre9, the library is updated to .NET 6. Should this line be updated, too?

**Comment by mristin** [comment]
@jh-isw thanks for spotting the mistake! Yes, the text should be updated.
