### ISSUE TITLE
Origin in rels is wrong

### ISSUE THREAD

**Issue by chbo-ml** [aas-core-works/aas-package3-csharp#39]
Hi,

I've noticed, that the origin in aasx package SPeicification has changed from vV2 to V3.

https://github.com/aas-core-works/aas-package3-csharp/blob/ed53a53e94585399360977a2da5dd76b744d767d/src/AasCore.Aas3.Package/Package.cs#L179

The"www." has been removed.

![image](https://github.com/aas-core-works/aas-package3-csharp/assets/159545135/71d52738-149b-44c9-bbe4-d414869515a4)

Many Greetings,
Christina Bornträger

**Comment by mristin** [comment]
@chbo-ml thanks! Do I understand correctly, we simply need to change this URI?

**Comment by mristin** [comment]
And what about the other URIs? I suppose also without "www."?

**Comment by chbo-ml** [comment]
Yes, as I understand the documentation in the threee URLS

```
            internal const string AasxOrigin =
                "http://www.admin-shell.io/aasx/relationships/aasx-origin";

            internal const string AasxSpec =
                "http://www.admin-shell.io/aasx/relationships/aas-spec";

            internal const string AasxSupplementary =
                "http://www.admin-shell.io/aasx/relationships/aas-suppl";

```
the www. has to be removed.

![image](https://github.com/aas-core-works/aas-package3-csharp/assets/159545135/25b9cce5-5408-4331-8184-831bc4ca505f)

**Comment by mristin** [comment]
@chbo-ml can you please test on your side, and then I'll release the next patch version?

**Comment by chbo-ml** [comment]
Look fine for me. Thanks!

**Comment by chbo-ml** [comment]
@mristin When will the new version be released?

**Comment by mristin** [comment]
@chbo-ml I planned it for today afternoon.

**Comment by mristin** [comment]
@chbo-ml the new version should be online: https://www.nuget.org/packages/AasCore.Aas3.Package
